CREATE DATABASE IF NOT EXISTS acme;

CREATE  TABLE TB_CONTATOS ( 
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL ,
EMAIL VARCHAR (100) NOT NULL,
TELEFONE VARCHAR (30) NOT NULL,
PRIMARY KEY (ID) 

);

CREATE  TABLE TB_USUARIOS ( 
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL ,
LOGIN VARCHAR (100) NOT NULL,
EMAIL VARCHAR (100) NOT NULL,
TELEFONES VARCHAR (100) NOT NULL,
SENHA VARCHAR (100) NOT NULL,
ATIVO BOOLEAN,
ADMINISTRADOR BOOLEAN,
VISITANTE BOOLEAN,
PRIMARY KEY (ID) 

);

INSERT INTO TB_USUARIOS (NOME,LOGIN,EMAIL,TELEFONES,SENHA,ATIVO,ADMINISTRADOR,VISITANTE) VALUES ("Carlos Barbosa","cbgomes","cbgomes@gmail.com",
"00000000","12345", true,true,true)